In [12]:
import numpy as np 

In [13]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ]) 

add = np.add(x,y) 
print(add)

sub = x-y 
print(sub)

mul = x*y 
print(mul) 

div = x/y 
print(div) 

remainder = x % y

print(remainder) 

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [14]:
# mathematical function 

# trigonometry 

# sin , cos , tan takes values in radian. Era radian chara ar kichu bujhe na.  

angle_deg = 90
angle_rad = np.deg2rad(angle_deg)

# cos_val = np.cos(x)
# print(cos_val)  # Radient e debe

sin_val = np.sin(angle_rad)  
print(sin_val)

1.0


In [15]:
#log 

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x) 
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [17]:
# sum 
s = np.sum(x)
print(s)

#prefix sum 
cumul =np.cumulative_sum(x)
print(cumul)

134
[ 10  18  34 134]


### Aro ase onk. Documentation suggest. 

In [19]:
#broadcasting 

x = np.array([ 10 , 8 , 16 , 100 ])

result = x + 2 

matrix = np.array([[10,20,30],
                [30,40,50]
               ])


result = matrix + 2 

vector = np.array([1,2,3,4])  #columns er size same na. Tai error asbe.  

result = matrix +vector
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 