In [ ]:
import numpy as np

In [7]:
#diag

inf = np.diag([1,3,5,7,9])
print(inf)
print(type(inf))
print(inf.shape)
print(inf.size)
print(inf.ndim)
print(inf.dtype)

[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 5 0 0]
 [0 0 0 7 0]
 [0 0 0 0 9]]
<class 'numpy.ndarray'>
(5, 5)
25
2
int64


In [8]:
#identity 1

inf = np.eye(5)  # row-column same. 
print(inf)
print(type(inf))
print(inf.shape)
print(inf.size)
print(inf.ndim)
print(inf.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>
(5, 5)
25
2
float64


In [11]:
#identity 2

inf = np.eye(5,7)  # row-column not same. 
print(inf)
print(type(inf))
print(inf.shape)
print(inf.size)
print(inf.ndim)
print(inf.dtype)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]
<class 'numpy.ndarray'>
(5, 7)
35
2
float64


In [19]:
#identity 2

inf = np.eye(5,7,3)  # row-column not same. 
print(inf)
print(type(inf))
print(inf.shape)
print(inf.size)
print(inf.ndim)
print(inf.dtype)

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
(5, 7)
35
2
float64
