In [1]:
import numpy as np

x = np.array([ 10 , 8 , 16 , 100 ])

(array([1]),)
[ 10   0  16 100]


In [9]:
# np.where( condition , x , y ) if true x , otherwise replace with y 

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array (Change korle index dey na. Dey array)
print(arr)

(array([2]),)
[ 10 100   0  16 100]


In [8]:
mat = np.array([[10,3,5],[8,4,9]])

index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array  (Change korle index dey na. Dey array)
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [6]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x) 
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2
