In [4]:
import numpy as np

inf = np.random.rand(2,3) # 0 -> 1 (float generate kore)   # (shape)

print(inf)
print(type(inf))
print(inf.shape)
print(inf.size)
print(inf.ndim)
print(inf.dtype)

[[0.16244358 0.84855102 0.87401534]
 [0.75177774 0.28621753 0.16781162]]
<class 'numpy.ndarray'>
(2, 3)
6
2
float64


In [9]:
inf = np.random.randint(1,10, (2,3))  # (range, (shape))

print(inf)
print(type(inf))
print(inf.shape)
print(inf.size)
print(inf.ndim)
print(inf.dtype)

[[9 1 2]
 [9 5 5]]
<class 'numpy.ndarray'>
(2, 3)
6
2
int32


In [11]:
inf = np.random.uniform(50,100, (2,3))  # (range, (shape))

print(inf)
print(type(inf))
print(inf.shape)
print(inf.size)
print(inf.ndim)
print(inf.dtype)

inf = np.random.uniform(50,100, (3,3,3))  # (range, (shape))

print(inf)
print(type(inf))
print(inf.shape)
print(inf.size)
print(inf.ndim)
print(inf.dtype)

[[85.65497696 71.59705002 50.65151425]
 [73.93538222 60.01461345 61.76848604]]
<class 'numpy.ndarray'>
(2, 3)
6
2
float64
[[[70.07961871 64.61214777 56.57934638]
  [53.43215473 85.01895339 92.8782339 ]
  [88.37926384 94.6511679  73.02771139]]

 [[50.63188918 79.38173675 99.98216033]
  [52.41430941 66.13339475 92.09887648]
  [76.9923313  88.43939767 61.91709699]]

 [[55.02043338 65.05036663 62.74595539]
  [63.77975503 76.56869867 93.51370357]
  [76.09048973 87.31519425 84.03641533]]]
<class 'numpy.ndarray'>
(3, 3, 3)
27
3
float64
