In [1]:
import numpy as np 

arr = np.random.randint(1 ,100 , size =(10,5)) # sample - 10 , feature - 5

print(arr)

[[21 28 91 48 69]
 [69 86 54 50 42]
 [96 41 16 85 77]
 [19 46 11 16 23]
 [32 93  4 48 13]
 [81 19 24 74  4]
 [34 86 15 91 73]
 [85 38 66 71 30]
 [70 63 43 62 78]
 [27 52 46 97 93]]


In [2]:
b = arr.reshape(5,10)

print(b)

[[21 28 91 48 69 69 86 54 50 42]
 [96 41 16 85 77 19 46 11 16 23]
 [32 93  4 48 13 81 19 24 74  4]
 [34 86 15 91 73 85 38 66 71 30]
 [70 63 43 62 78 27 52 46 97 93]]


In [3]:
flatten = b.flatten()

print(flatten)

[21 28 91 48 69 69 86 54 50 42 96 41 16 85 77 19 46 11 16 23 32 93  4 48
 13 81 19 24 74  4 34 86 15 91 73 85 38 66 71 30 70 63 43 62 78 27 52 46
 97 93]


In [6]:
column_wise_flattening = np.ravel(b,order= 'C') 

print(column_wise_flattening) 

[21 28 91 48 69 69 86 54 50 42 96 41 16 85 77 19 46 11 16 23 32 93  4 48
 13 81 19 24 74  4 34 86 15 91 73 85 38 66 71 30 70 63 43 62 78 27 52 46
 97 93]


In [7]:
column_wise_flattening = np.ravel(b,order= 'F') 

print(column_wise_flattening) 

[21 96 32 34 70 28 41 93 86 63 91 16  4 15 43 48 85 48 91 62 69 77 13 73
 78 69 19 81 85 27 86 46 19 38 52 54 11 24 66 46 50 16 74 71 97 42 23  4
 30 93]


In [12]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))
print(a)
print(b)

[[5 5 3]
 [8 4 6]]
[[26 21 23]
 [25 24 28]]


In [11]:
con_row = np.concatenate((a,b),axis=0) # row wise 

print(con_row)

[[ 1  9  1]
 [ 7  9  6]
 [22 27 25]
 [29 22 26]]


In [10]:
con_row = np.concatenate((a,b),axis=1) # row wise 

print(con_row)

[[ 1  9  1 22 27 25]
 [ 7  9  6 29 22 26]]


In [13]:
# error 

# row wise concetanate -> column same 
# column wise concetanate -> row same 

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [14]:
# transpose 

mat = np.array([[10,20,30],
                [30,40,50]
               ])


transpose = mat.T

print(transpose) 

[[10 30]
 [20 40]
 [30 50]]


In [21]:
# array split 

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)  # soman soman vag korte na parle error debe na. 

print(splitted_array)  

# split -> equal division 
splitted_array = np.split(a,3)   # soman soman vag korte na parle error debe. 
print(splitted_array)

[8 6 3 3 7 3 5 5 5 5]
[array([8, 6, 3, 3], dtype=int32), array([7, 3, 5], dtype=int32), array([5, 5, 5], dtype=int32)]


ValueError: array split does not result in an equal division