In [26]:
import numpy as np
import pandas as pd

my_list = [10, 20, 30, 40, 50]

print(data)
pd_list = pd.Series(my_list)
pd_list

# print(pd_list.index)
# print(type(pd_list))

data = np.resize(my_list, (4,3))
dtf = pd.DataFrame(data,columns=['Name','Age','City'])
dtf

[[10 20 30]
 [40 50 10]
 [20 30 40]
 [50 10 20]]


Name  Age  City
0    10   20    30
1    40   50    10
2    20   30    40
3    50   10    20

In [33]:
np.size(dtf.columns)

3

In [34]:
np.size(dtf.index)

4

In [37]:
dtf.describe()

Name        Age       City
count   4.000000   4.000000   4.000000
mean   30.000000  27.500000  25.000000
std    18.257419  17.078251  12.909944
min    10.000000  10.000000  10.000000
25%    17.500000  17.500000  17.500000
50%    30.000000  25.000000  25.000000
75%    42.500000  35.000000  32.500000
max    50.000000  50.000000  40.000000

In [41]:
data2 = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
dd = pd.DataFrame(data2)
dd

Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [42]:
dd['Quantity']

0    100
1     60
2    200
3    150
Name: Quantity, dtype: int64

In [51]:
dd.iloc[2]

Product     Eraser
Price            5
Quantity       200
Name: 2, dtype: object

In [55]:
dd.loc[1,['Product','Price','Quantity']]

Product    Book
Name: 1, dtype: object

In [57]:
dd.loc[0]

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

In [64]:
dd

Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [72]:
dd.iloc[:,1]

0    10
1    50
2     5
3     7
Name: Price, dtype: int64

In [73]:
data = {
    'Name': ['Rahim', 'Karim', 'Sakib', 'Tamim'],
    'Math': [85, 78, 92, 88],
    'Physics': [80, 75, 90, 84]
}

df = pd.DataFrame(data)
df

Name  Math  Physics
0  Rahim    85       80
1  Karim    78       75
2  Sakib    92       90
3  Tamim    88       84

In [76]:
df.drop('Physics',inplace=True, axis=1)

In [77]:
df

Name  Math
0  Rahim    85
1  Karim    78
2  Sakib    92
3  Tamim    88

In [79]:
df.drop(2,inplace=True)

In [80]:
df

Name  Math
0  Rahim    85
1  Karim    78
3  Tamim    88

In [81]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana"],
    "Department": ["HR", "IT", "Finance", "Marketing"],
    "Salary": [50000, 65000, 60000, 55000]
}

df = pd.DataFrame(data)
df

Name Department  Salary
0    Alice         HR   50000
1      Bob         IT   65000
2  Charlie    Finance   60000
3    Diana  Marketing   55000

In [83]:
sorted = df.sort_values(['Salary','Name'],ascending=[1,0])
sorted

Name Department  Salary
0    Alice         HR   50000
3    Diana  Marketing   55000
2  Charlie    Finance   60000
1      Bob         IT   65000

In [84]:
sorted2 = df.sort_values('Salary')
sorted2

Name Department  Salary
0    Alice         HR   50000
3    Diana  Marketing   55000
2  Charlie    Finance   60000
1      Bob         IT   65000

In [92]:
data = {
    "Name": ["Rahim", "Karim", "Sakib", "Tamim", "Mushfiq", "Shanto", "Litton", "Mehedi"],
    "Score": [78, 41, 92, 88, 55, 75, 44, 59]
}
df = pd.DataFrame(data)
df

Name  Score
0    Rahim     78
1    Karim     85
2    Sakib     92
3    Tamim     88
4  Mushfiq     81
5   Shanto     75
6   Litton     89
7   Mehedi     83

In [95]:
filtered = df.loc[(df['Score'] > 40) & (df['Score'] < 60)]
filtered

Name  Score
0    Rahim     78
1    Karim     85
3    Tamim     88
4  Mushfiq     81
5   Shanto     75
6   Litton     89
7   Mehedi     83