In [9]:
import numpy as np

x = np.array([[40, 90, 22, 45, 10],[40,54,26, 55, 10]])
y = np.sort(x, axis=1)  # new copy toiri kore
print(y)
print(x)

x = np.array([[40, 90, 22, 45, 10],[40,54,26, 55, 10]])
y = np.sort(x, axis=0)  # new copy toiri kore
print(y)
print(x)

[[40 54 22 45 10]
 [40 90 26 55 10]]
[[40 90 22 45 10]
 [40 54 26 55 10]]
